#!/bin/sh

subdirs="$@"

## configure just includes this file with ". makesource"
if [ -z "${0%*./configure}" ]
then
 echo \"makesource\" called from configure
 subdirs=""
fi

if [ -z "$subdirs" ]
then
  subdirs="../Manips  ../Particles ../Base ../MarkEx ../Pixes ../Controls ../Nongeos  ../Geos ../openGL" 
fi

for j in $subdirs
do
    echo Sources for $j
    cd $j
    echo SOURCES= \\ > Make.source
    for i in `ls *.cpp`
    do
         echo $i \\ >> Make.source
    done
    echo >> Make.source
done

cd ../Gnu

for j in $subdirs
do
    cp Makefile.subdir $j/Makefile.in
done

