#!/bin/sh

subdirs="../Manips  ../Particles ../Base ../MarkEx ../Pixes ../Controls ../Nongeos  ../Geos ../TV ../openGL ../yuv" 

for j in $subdirs
do
    echo Sources for $j
    cd $j
    echo SOURCES= \\ > Make.source
    for i in `ls *.cpp`
    do
         echo $i \\ >> Make.source
    done
    echo >> Make.source
done

cd ../Gnu

for j in $subdirs
do
    cp Makefile.subdir $j/Makefile.in
done

