#!/bin/sh

#AUXPATH=../AuxLibs
AUXPATH=../../../GemLibs

if [ "$1" = "clean" ]
then

echo Cleaning up Auxilliary Libraries
echo =============================
echo

echo CLEANING LIBORB
(cd $AUXPATH/liborb;make clean )

echo
echo Finished cleaning Auxilliary Libraries
echo ======================================

else


echo Building Auxilliary Libraries
echo =============================
echo

echo BUILDING LIBORB
(cd $AUXPATH/liborb;make )

echo
echo Finished building Auxilliary Libraries
echo ======================================

fi
