---
###################################################
### configuration templates (to be used for snapshot and release builds)
variables:
  PDVERSION:
    value: 0.54-1
    description: "The Pd-version against which to build"
  LANG:
    value: "C"
    description: ""
  MACOSX_DEPLOYMENT_TARGET:
    # compatibility for older OSX-builds (<mutex> requires C++11, available since OSX10.9/Mavericks)
    value: "10.9"
    description: "For macOS builds, specify the minimum version where Gem should run on"
  ARTIFACTSDIR:
    value: 'artifacts'
    description: ""
  IEM_CI_TMPDIR:
    value: ".git-ci/_tmp/"
    description: ""
  IEM_CI_JOBS:
    value: ""
    description: "list of jobs to run (leave empty for all jobs)"
  gem_defaultwindow:
    value: "gemglfw3window"
    description: "default window backend"


stages:
  - build
  - test
  - sign
  - deploy

.artifacts:
  artifacts:
    name: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_JOB_NAME%_*}
    paths:
      - "${ARTIFACTSDIR}"
    when: always

.run-selected:
  rules:
    # run if IEM_CI_JOBS list is empty
    - if: $IEM_CI_JOBS == ""
    # run if CI_JOB_NAME is in the IEM_CI_JOBS list
    - if: $CI_JOB_NAME =~ $IEM_CI_JOBS
    # otherwise, don't run
    - when: never

.script:zsh_compat: &script_zsh_compat
  - | # zsh fixes
    set -o shwordsplit || true     # zsh doesn't do wordsplitting by default...
    set -o nonomatch   || true     # zsh bails out if globbing patterns do not expand

.build:
  stage: build
  script:
    - *script_zsh_compat
    - echo building against Pd-${PDVERSION}
    - echo building with ${NUMBER_OF_PROCESSORS:=$(nproc || sysctl -n hw.ncpu || echo 1)} CPUs
    - tools/systeminfo.sh || true
    - date
    - g++ -v
    - mkdir -pv "${ARTIFACTSDIR}"
    - autoreconf -fiv || ./autogen.sh
    - ./configure --disable-dependency-tracking ${TARGETARCH:+--host=}${TARGETARCH} ${fat_binary:+--enable-fat-binary=}${fat_binary} ${PDDIR:+--with-pd=}${PDDIR} ${pd_extension:+--with-extension=}${pd_extension} ${gem_defaultwindow:+--with-defaultwindow=}${gem_defaultwindow} --with-DeckLink=local || true
    - test -n "${CI_COMMIT_TAG}" || cp -v config.log "${ARTIFACTSDIR}"
    - make check -j"${NUMBER_OF_PROCESSORS}"
    - make install DESTDIR=$(pwd)/${ARTIFACTSDIR}/${CI_JOB_NAME%_*} libdir=/ extradir=/Gem includedir=/Gem/include
    # finally split the binaries from the debug information
    - base_dir_ci=$(pwd)
    - cd "$(pwd)/${ARTIFACTSDIR}/${CI_JOB_NAME%_*}/Gem"
    - du -sh
    - |
      "${base_dir_ci}/.git-ci/split-debug" ${pd_extension:+*.${pd_extension}} *.pd_* *.?_* *.dll *.so || echo "ignoring problems when splitting debug info"
    - du -sh
    - cd "${base_dir_ci}"
    - test "${result}" != "skip" || exit 77
  allow_failure:
    exit_codes:
      - 77

.build:linux:
  extends:
    - .build
  image: registry.git.iem.at/devtools/docker/debiancross:amd64
  before_script:
    - tools/systeminfo.sh || true
    - date
    - mkdir -p /etc/apt/sources.list.d/
    - find /etc/apt/sources.list /etc/apt/sources.list.d/ -name "*.list" -type f -exec egrep "^deb " {} ";" | sed -e 's|^deb |deb-src |' > /etc/apt/sources.list.d/${CI_COMMIT_REF_SLUG}.list
    - apt-get update
    - apt-get install ${TARGETDEBARCH:+-a}${TARGETDEBARCH} puredata-dev puredata-core
    - apt-get build-dep ${TARGETDEBARCH:+-a}${TARGETDEBARCH} gem || true
    - g++ -v

.build:macos:
  extends:
    - .build
  tags:
    - tart
  image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  retry:
    max: 1
    when:
      - runner_system_failure
  variables:
    CXXFLAGS: "-std=c++11 -g -O2"
    fat_binary: "x86_64,arm64"
    HOMEBREW_NO_ANALYTICS: 1
    HOMEBREW_NO_INSTALL_UPGRADE: 1
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
    CODESIGNFLAGS: --timestamp --strict --force
  before_script:
    - *script_zsh_compat
    - tools/systeminfo.sh || true
    - date
    # cleanup brew (tart is broken)
    - brew uninstall -f android-ndk android-sdk temurin8 libimobiledevice ideviceinstaller ios-deploy fastlane libusb libusbmuxd || true
    - brew unlink libpng || true
    - brew list --full-name || true
    - brew update || true
    # make sure we have a good gitlab runner
    - (which gitlab-runner; gitlab-runner --version) || brew install gitlab-runner || true
    - (which gitlab-runner; gitlab-runner --version) || true

    # download Pd
    - rm -rf /Applications/Pd*.app/
    - curl -sL http://msp.ucsd.edu/Software/pd-${PDVERSION}.mac.tar.gz | tar --extract --gzip --directory /Applications/ || mkdir -p "${IEM_CI_TMPDIR}"
    # if there was no tarball, try to get a zip-file
    - test ! -d "${IEM_CI_TMPDIR}" || curl -sL -o "${IEM_CI_TMPDIR}"/Pd.zip http://msp.ucsd.edu/Software/pd-${PDVERSION}.macos.zip
    - test ! -f "${IEM_CI_TMPDIR}"/Pd.zip || unzip "${IEM_CI_TMPDIR}"/Pd.zip -d "${IEM_CI_TMPDIR}"
    # the ZIP-file shoud contain a .dmg containing Pd
    - |
      for dmg in "${IEM_CI_TMPDIR}"/Pd*.dmg; do break; done
    - pddisk=""
    - test ! -f "${dmg}" || pddisk=$(hdiutil attach "${dmg}" 2>/dev/null | egrep "^/.*/Volumes/" | tail -1 | awk '{print $NF}')
    - rm -rf "${dmg}"
    - |
      for app in "${pddisk}"/Pd*.app "${IEM_CI_TMPDIR}"/Pd*.app; do if test -d "${app}"; then cp -r "${app}" /Applications/; break; fi; done
    - test ! -d "${pddisk}" || umount "${pddisk}"
    - |
      rm -rf "${IEM_CI_TMPDIR}"
      dmg=""
      pddisk=""
      app=""

    - export PD=$(find /Applications/Pd*.app/Contents/Resources/bin/ type f -name pd -print -quit)
    - export PDDIR=$(find /Applications/Pd*.app/Contents/Resources -maxdepth 1 -type d -print -quit)
    - echo "PD=${PD}"
    - echo "PDDIR=${PDDIR}"
    - brew bundle --no-upgrade --file=.git-ci/macOS.brew || true
    - brew list --full-name || true
    # older versions of assimp are broken with clang>=14
    - sed -e 's|^\([[:space:]]*mTextureCoordsNames = new aiString \*\[AI_MAX_NUMBER_OF_TEXTURECOORDS\]\) {};[[:space:]]*$|\1; for (size_t i=0; i<AI_MAX_NUMBER_OF_TEXTURECOORDS; ++i) {mTextureCoordsNames[i] = nullptr;}|' -i.bak "$(brew --cellar)"/assimp-fat/5.2*/include/assimp/mesh.h || true
    - /usr/local/opt/gettext/bin/gettextize || true
    - date
    - echo "MACOSX_DEPLOYMENT_TARGET=${MACOSX_DEPLOYMENT_TARGET}"
  after_script:
    - *script_zsh_compat
    - mkdir -p "${ARTIFACTSDIR}/${CI_JOB_NAME%_*}"
    - find "${ARTIFACTSDIR}/${CI_JOB_NAME%_*}" -type f "(" -name "*.${pd_extension:-d_*}" -o -name "*.pd_darwin" -o -name "*.so" ")" -exec .git-ci/localdeps.macos.sh {} +
    - IEM_SIGN_SRCDIR="${ARTIFACTSDIR}/${CI_JOB_NAME%_*}"
    - !reference [.script:codesign:macos]

.build:w64:
  extends:
    - .build
  tags:
    - windows
  variables:
    IEMCI_CONFIGURATIONS: mingw64
    pd_downloadsuffix: .msw.zip
  before_script:
    - tools/systeminfo.sh || true
    - export PDDIR="$(pwd)/_pd"
    - downloadfile="pd-${PDVERSION}${pd_downloadsuffix}"
    - echo wget -q -O "${downloadfile}" "http://msp.ucsd.edu/Software/pd-${PDVERSION}${pd_downloadsuffix}"
    - wget -q -O "${downloadfile}" "http://msp.ucsd.edu/Software/pd-${PDVERSION}${pd_downloadsuffix}"
    - mkdir -p "${PDDIR}"
    - test "x${downloadfile}" = "x${downloadfile%.zip}" || unzip -q "${downloadfile}" -d "${PDDIR}"
    - mv -v "${PDDIR}"/*/* "${PDDIR}"
    - rm -f "${downloadfile}"
    - rm -f "${PDDIR}"/bin/msvcr*.dll
    - export PD="${PDDIR}/bin/pd.com"
    - result=0
    - pacman --noconfirm -S --needed $(cat .git-ci/msys2.pacman  | sed -e 's|#.*||' -e "s|@MINGW@|${MINGW_PACKAGE_PREFIX}-|") || result=$?
    # if pacman failed, try to continue (but do not mark the run as 'success')
    - echo "pacman returned ${result}"
    - test "${result}" = "0" || result="skip"
  after_script:
    - mkdir -p "${ARTIFACTSDIR}/${CI_JOB_NAME%_*}"
    - find "${ARTIFACTSDIR}/${CI_JOB_NAME%_*}" -type f "(" -name "*.${pd_extension:-m_*}" -o -name "*.dll" -o -name "*.exe" -o -name "*.com" ")" -exec .git-ci/localdeps.win.sh {} +

.build:w32:
  extends:
    - .build:w64
  variables:
    IEMCI_CONFIGURATIONS: mingw32
    pd_downloadsuffix: -i386.msw.zip
    CXXFLAGS: "-g -O2 -fexceptions"

###################################################
### the actual jobs: (linux,macos,windows)*(release,snapshot)

Source:
  extends:
    - .artifacts
    - .run-selected
  stage: build
  before_script:
    # we need 'git' to create a source package
    - apt-get update && apt-get --no-install-recommends -y install git
  script:
    # create a source package
    - git archive --format=tar --prefix="${ARTIFACTSDIR}/Source/${CI_PROJECT_NAME}/" HEAD | tar xf -

Linux-amd64-32:
  extends:
    - .build:linux
    - .artifacts
    - .run-selected
Darwin-fat-32:
  extends:
    - .build:macos
    - .artifacts
    - .run-selected
Windows-i386-32:
  extends:
    - .build:w32
    - .artifacts
    - .run-selected
Windows-amd64-32:
  extends:
    - .build:w64
    - .artifacts
    - .run-selected

distcheck:
  extends:
    - .build:linux
    - .run-selected
  stage: test
  dependencies: []
  needs: []
  script:
    - tools/systeminfo.sh || true
    - date
    - g++ -v
    - mkdir -pv "${ARTIFACTSDIR}"
    - autoreconf -fiv || ./autogen.sh
    - ./configure --disable-dependency-tracking ${TARGETARCH:+--host=}${TARGETARCH} --without-ALL ${PDDIR:+--with-pd=}${PDDIR} || true
    - make distcheck -j2

# check if the 'dist' package includes all relevant files
# ignored files are read from the .git-ci/nodist file
nodist:
  stage: test
  dependencies: []
  needs: []
  rules:
    # run if IEM_CI_JOBS list is empty
    - if: $IEM_CI_JOBS == ""
      exists:
        - ".git-ci/nodist"
    # run if CI_JOB_NAME is in the IEM_CI_JOBS list
    - if: $CI_JOB_NAME =~ $IEM_CI_JOBS
      exists:
        - ".git-ci/nodist"
    # otherwise, don't run
    - when: never
  image: debian:stable
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends git build-essential autoconf automake libtool pkg-config freeglut3-dev puredata-dev
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global --list || true
  script:
    ## pre-cleanup
    # get rid of gitignores
    - find . -name .gitignore -delete
    - git commit -a -m "Drop .gitignore files"
    ## create 'make dist' package
    - autoreconf -fiv || ./autogen.sh
    - ./configure --without-ALL
    - mkdir -p .git-ci
    - rm -rf .git-ci/Gem .git-ci/Gem.*gz
    # create 'make dist' package
    - make dist distdir=.git-ci/Gem
    ## restore the source dir from the 'make dist' package
    - find . -mindepth 1 -maxdepth 1 "(" -not -name ".git" -a -not -name ".git-ci" ")" -exec rm -rf {} +
    - tar -x -f .git-ci/Gem.*gz --strip-components=2
    ## ensure that the restored folder contains only the changes we want to see
    # drop files not tracked by git (e.g. generated autotools helpers)
    - git clean -fdx
    # restore files that need not be distributed
    - git checkout --pathspec-from-file=.git-ci/nodist
    ## show differences
    - git status -s
    - git diff-index --quiet HEAD


macOS:notarize:
  stage: deploy
  image: python:alpine
  dependencies:
    - Darwin-fat-32
  needs:
    - Darwin-fat-32
  variables:
    IEM_NOTARIZE_SRCDIR: artifacts
    IEM_NOTARIZE_ARCHIVE: Gem.zip
  before_script:
    - apk add zip git
  script:
    - !reference [.script:notarize:macos]
  allow_failure: true


deken:
  extends:
    - .run-selected
  stage: deploy
  image: registry.git.iem.at/pd/deken:latest
  before_script:
    - apt-get update -y
    - apt-get install -y --no-install-recommends git
    # per default, use the tag as the version
    - version="${CI_COMMIT_TAG}"
    - gitversion="$(git describe --always)"
    # if there is not tag (but we are on the default branch), publish a snapshot
    - test -n "${version}" || test "${CI_COMMIT_BRANCH}" != "${CI_DEFAULT_BRANCH}" || version="$(git describe --abbrev=0)-snapshot"
    - version="${version#v}"
    - echo "${version}"
    - test -n "${CI_COMMIT_TAG}" || test ! -e .git-ci/README.snapshot.pd.in || sed -e "s|@build-date@|${CI_PIPELINE_CREATED_AT}|g" -e "s|@version@|${gitversion}|g" .git-ci/README.snapshot.pd.in > README.deken.pd
  script:
    - chmod -R u+rw,go-w ${ARTIFACTSDIR}/
    # remove ltlib leftovers
    - find ${ARTIFACTSDIR}/ "(" -name "*.la" -or -name "*.a" ")" -delete
    # remove debug information
    - find ${ARTIFACTSDIR}/ -name "*.debug" -delete
    # inject any README.deken
    - for f in README.deken.*; do [ -e "${f}" ] || continue; for d in ${ARTIFACTSDIR}/*/${CI_PROJECT_NAME}/; do cp "${f}" "${d}" || true; done; done
    # create deken packages
    - for d in ${ARTIFACTSDIR}/*/${CI_PROJECT_NAME}/; do deken package --version="${version}" "${d}"; done
    # upload deken packages
    - test -z "${version}" || test -z "${DEKEN_USERNAME}" || test -z "${DEKEN_PASSWORD}" || deken upload --no-source-error ./*.dek
  artifacts:
    name: deken-package
    paths:
      - ./*.dek
      - ./*.dek.*

# out SAST jobs don't have any prerequisites, so run them early...
sast:
  dependencies: []
  needs: []

include:
  # for the codesign templates
  - https://git.iem.at/pd/iem-ci/-/raw/main/pd-lib-builder/codesign.yml
  # additionally run some static code analysis
  - template: Security/SAST.gitlab-ci.yml
