////////////////////////////////////////////////////////
//
// GEM - Graphics Environment for Multimedia
//
// Copyleft (c) IOhannes m zmölnig . zmoelnig@iem.kug.ac.at . forum::für::umläute . IEM
//
//    For information on usage and redistribution, and for a DISCLAIMER OF ALL
//    WARRANTIES, see the file, "GEM.LICENSE.TERMS" in this distribution.
//
/////////////////////////////////////////////////////////
/* -------------------------- setup function ------------------------------ */

extern "C" {

   void GEMglAccum_setup();
   void GEMglAlphaFunc_setup();
   void GEMglBegin_setup();
   void GEMglBitmap_setup();
   void GEMglBlendFunc_setup();
   void GEMglClear_setup();
   void GEMglClearAccum_setup();
   void GEMglClearColor_setup();
   void GEMglClearDepth_setup();
   void GEMglClearIndex_setup();
   void GEMglClearStencil_setup();
   void GEMglColor3b_setup();
   void GEMglColor3bv_setup();
   void GEMglColor3d_setup();
   void GEMglColor3dv_setup();
   void GEMglColor3f_setup();
   void GEMglColor3fv_setup();
   void GEMglColor3i_setup();
   void GEMglColor3iv_setup();
   void GEMglColor3s_setup();
   void GEMglColor3sv_setup();
   void GEMglColor3ub_setup();
   void GEMglColor3ubv_setup();
   void GEMglColor3ui_setup();
   void GEMglColor3uiv_setup();
   void GEMglColor3us_setup();
   void GEMglColor3usv_setup();
   void GEMglColor4b_setup();
   void GEMglColor4bv_setup();
   void GEMglColor4d_setup();
   void GEMglColor4dv_setup();
   void GEMglColor4f_setup();
   void GEMglColor4fv_setup();
   void GEMglColor4i_setup();
   void GEMglColor4iv_setup();
   void GEMglColor4s_setup();
   void GEMglColor4sv_setup();
   void GEMglColor4ub_setup();
   void GEMglColor4ubv_setup();
   void GEMglColor4ui_setup();
   void GEMglColor4uiv_setup();
   void GEMglColor4us_setup();
   void GEMglColor4usv_setup();
   void GEMglColorMask_setup();
   void GEMglColorMaterial_setup();
   void GEMglCopyPixels_setup();
   void GEMglCullFace_setup();
   void GEMglDepthFunc_setup();
   void GEMglDepthMask_setup();
   void GEMglDepthRange_setup();
   void GEMglDisable_setup();
   void GEMglDrawBuffer_setup();
   void GEMglEdgeFlag_setup();
   void GEMglEnable_setup();
   void GEMglEnd_setup();
   void GEMglFinish_setup();
   void GEMglFlush_setup();
   void GEMglFrontFace_setup();
   void GEMglFrustum_setup();
   void GEMglHint_setup();
   void GEMglIndexMask_setup();
   void GEMglIndexd_setup();
   void GEMglIndexf_setup();
   void GEMglIndexi_setup();
   void GEMglIndexs_setup();
   void GEMglLightModelf_setup();
   void GEMglLightModeli_setup();
   void GEMglLightf_setup();
   void GEMglLighti_setup();
   void GEMglLineStipple_setup();
   void GEMglLineWidth_setup();
   void GEMglLoadIdentity_setup();
   void GEMglLogicOp_setup();
   void GEMglMaterialf_setup();
   void GEMglMateriali_setup();
   void GEMglMatrixMode_setup();
   void GEMglNormal3b_setup();
   void GEMglNormal3bv_setup();
   void GEMglNormal3d_setup();
   void GEMglNormal3dv_setup();
   void GEMglNormal3f_setup();
   void GEMglNormal3fv_setup();
   void GEMglNormal3i_setup();
   void GEMglNormal3iv_setup();
   void GEMglNormal3s_setup();
   void GEMglNormal3sv_setup();
   void GEMglOrtho_setup();
   void GEMglPixelStoref_setup();
   void GEMglPixelStorei_setup();
   void GEMglPixelTransferf_setup();
   void GEMglPixelTransferi_setup();
   void GEMglPixelZoom_setup();
   void GEMglPointSize_setup();
   void GEMglPolygonMode_setup();
   void GEMglPolygonOffset_setup();
   void GEMglPopAttrib_setup();
   void GEMglPopMatrix_setup();
   void GEMglPushAttrib_setup();
   void GEMglPushMatrix_setup();
   void GEMglRasterPos2d_setup();
   void GEMglRasterPos2dv_setup();
   void GEMglRasterPos2f_setup();
   void GEMglRasterPos2fv_setup();
   void GEMglRasterPos2i_setup();
   void GEMglRasterPos2iv_setup();
   void GEMglRasterPos2s_setup();
   void GEMglRasterPos2sv_setup();
   void GEMglRasterPos3d_setup();
   void GEMglRasterPos3dv_setup();
   void GEMglRasterPos3f_setup();
   void GEMglRasterPos3fv_setup();
   void GEMglRasterPos3i_setup();
   void GEMglRasterPos3iv_setup();
   void GEMglRasterPos3s_setup();
   void GEMglRasterPos3sv_setup();
   void GEMglRasterPos4d_setup();
   void GEMglRasterPos4dv_setup();
   void GEMglRasterPos4f_setup();
   void GEMglRasterPos4fv_setup();
   void GEMglRasterPos4i_setup();
   void GEMglRasterPos4iv_setup();
   void GEMglRasterPos4s_setup();
   void GEMglRasterPos4sv_setup();
   void GEMglRectd_setup();
   void GEMglRectf_setup();
   void GEMglRecti_setup();
   void GEMglRects_setup();
   void GEMglRotated_setup();
   void GEMglRotatef_setup();
   void GEMglScaled_setup();
   void GEMglScalef_setup();
   void GEMglScissor_setup();
   void GEMglShadeModel_setup();
   void GEMglStencilFunc_setup();
   void GEMglStencilMask_setup();
   void GEMglStencilOp_setup();
   void GEMglTexCoord1d_setup();
   void GEMglTexCoord1dv_setup();
   void GEMglTexCoord1f_setup();
   void GEMglTexCoord1fv_setup();
   void GEMglTexCoord1i_setup();
   void GEMglTexCoord1iv_setup();
   void GEMglTexCoord1s_setup();
   void GEMglTexCoord1sv_setup();
   void GEMglTexCoord2d_setup();
   void GEMglTexCoord2dv_setup();
   void GEMglTexCoord2f_setup();
   void GEMglTexCoord2fv_setup();
   void GEMglTexCoord2i_setup();
   void GEMglTexCoord2iv_setup();
   void GEMglTexCoord2s_setup();
   void GEMglTexCoord2sv_setup();
   void GEMglTexCoord3d_setup();
   void GEMglTexCoord3dv_setup();
   void GEMglTexCoord3f_setup();
   void GEMglTexCoord3fv_setup();
   void GEMglTexCoord3i_setup();
   void GEMglTexCoord3iv_setup();
   void GEMglTexCoord3s_setup();
   void GEMglTexCoord3sv_setup();
   void GEMglTexCoord4d_setup();
   void GEMglTexCoord4dv_setup();
   void GEMglTexCoord4f_setup();
   void GEMglTexCoord4fv_setup();
   void GEMglTexCoord4i_setup();
   void GEMglTexCoord4iv_setup();
   void GEMglTexCoord4s_setup();
   void GEMglTexCoord4sv_setup();
   void GEMglTexEnvf_setup();
   void GEMglTexEnvi_setup();
   void GEMglTexGend_setup();
   void GEMglTexGenf_setup();
   void GEMglTexGeni_setup();
   void GEMglTexParameterf_setup();
   void GEMglTexParameteri_setup();
   void GEMglTranslated_setup();
   void GEMglTranslatef_setup();
   void GEMglVertex2d_setup();
   void GEMglVertex2dv_setup();
   void GEMglVertex2f_setup();
   void GEMglVertex2fv_setup();
   void GEMglVertex2i_setup();
   void GEMglVertex2iv_setup();
   void GEMglVertex2s_setup();
   void GEMglVertex2sv_setup();
   void GEMglVertex3d_setup();
   void GEMglVertex3dv_setup();
   void GEMglVertex3f_setup();
   void GEMglVertex3fv_setup();
   void GEMglVertex3i_setup();
   void GEMglVertex3iv_setup();
   void GEMglVertex3s_setup();
   void GEMglVertex3sv_setup();
   void GEMglVertex4d_setup();
   void GEMglVertex4dv_setup();
   void GEMglVertex4f_setup();
   void GEMglVertex4fv_setup();
   void GEMglVertex4i_setup();
   void GEMglVertex4iv_setup();
   void GEMglVertex4s_setup();
   void GEMglVertex4sv_setup();
   void GEMglViewport_setup();


   void openGL_setup() {
      GEMglAccum_setup();
      GEMglAlphaFunc_setup();
      GEMglBegin_setup();
      GEMglBitmap_setup();
      GEMglBlendFunc_setup();
      GEMglClear_setup();
      GEMglClearAccum_setup();
      GEMglClearColor_setup();
      GEMglClearDepth_setup();
      GEMglClearIndex_setup();
      GEMglClearStencil_setup();
      GEMglColor3b_setup();
      GEMglColor3bv_setup();
      GEMglColor3d_setup();
      GEMglColor3dv_setup();
      GEMglColor3f_setup();
      GEMglColor3fv_setup();
      GEMglColor3i_setup();
      GEMglColor3iv_setup();
      GEMglColor3s_setup();
      GEMglColor3sv_setup();
      GEMglColor3ub_setup();
      GEMglColor3ubv_setup();
      GEMglColor3ui_setup();
      GEMglColor3uiv_setup();
      GEMglColor3us_setup();
      GEMglColor3usv_setup();
      GEMglColor4b_setup();
      GEMglColor4bv_setup();
      GEMglColor4d_setup();
      GEMglColor4dv_setup();
      GEMglColor4f_setup();
      GEMglColor4fv_setup();
      GEMglColor4i_setup();
      GEMglColor4iv_setup();
      GEMglColor4s_setup();
      GEMglColor4sv_setup();
      GEMglColor4ub_setup();
      GEMglColor4ubv_setup();
      GEMglColor4ui_setup();
      GEMglColor4uiv_setup();
      GEMglColor4us_setup();
      GEMglColor4usv_setup();
      GEMglColorMask_setup();
      GEMglColorMaterial_setup();
      GEMglCopyPixels_setup();
      GEMglCullFace_setup();
      GEMglDepthFunc_setup();
      GEMglDepthMask_setup();
      GEMglDepthRange_setup();
      GEMglDisable_setup();
      GEMglDrawBuffer_setup();
      GEMglEdgeFlag_setup();
      GEMglEnable_setup();
      GEMglEnd_setup();
      GEMglFinish_setup();
      GEMglFlush_setup();
      GEMglFrontFace_setup();
      GEMglFrustum_setup();
      GEMglHint_setup();
      GEMglIndexMask_setup();
      GEMglIndexd_setup();
      GEMglIndexf_setup();
      GEMglIndexi_setup();
      GEMglIndexs_setup();
      GEMglLightModelf_setup();
      GEMglLightModeli_setup();
      GEMglLightf_setup();
      GEMglLighti_setup();
      GEMglLineStipple_setup();
      GEMglLineWidth_setup();
      GEMglLoadIdentity_setup();
      GEMglLogicOp_setup();
      GEMglMaterialf_setup();
      GEMglMateriali_setup();
      GEMglMatrixMode_setup();
      GEMglNormal3b_setup();
      GEMglNormal3bv_setup();
      GEMglNormal3d_setup();
      GEMglNormal3dv_setup();
      GEMglNormal3f_setup();
      GEMglNormal3fv_setup();
      GEMglNormal3i_setup();
      GEMglNormal3iv_setup();
      GEMglNormal3s_setup();
      GEMglNormal3sv_setup();
      GEMglOrtho_setup();
      GEMglPixelStoref_setup();
      GEMglPixelStorei_setup();
      GEMglPixelTransferf_setup();
      GEMglPixelTransferi_setup();
      GEMglPixelZoom_setup();
      GEMglPointSize_setup();
      GEMglPolygonMode_setup();
      GEMglPolygonOffset_setup();
      GEMglPopAttrib_setup();
      GEMglPopMatrix_setup();
      GEMglPushAttrib_setup();
      GEMglPushMatrix_setup();
      GEMglRasterPos2d_setup();
      GEMglRasterPos2dv_setup();
      GEMglRasterPos2f_setup();
      GEMglRasterPos2fv_setup();
      GEMglRasterPos2i_setup();
      GEMglRasterPos2iv_setup();
      GEMglRasterPos2s_setup();
      GEMglRasterPos2sv_setup();
      GEMglRasterPos3d_setup();
      GEMglRasterPos3dv_setup();
      GEMglRasterPos3f_setup();
      GEMglRasterPos3fv_setup();
      GEMglRasterPos3i_setup();
      GEMglRasterPos3iv_setup();
      GEMglRasterPos3s_setup();
      GEMglRasterPos3sv_setup();
      GEMglRasterPos4d_setup();
      GEMglRasterPos4dv_setup();
      GEMglRasterPos4f_setup();
      GEMglRasterPos4fv_setup();
      GEMglRasterPos4i_setup();
      GEMglRasterPos4iv_setup();
      GEMglRasterPos4s_setup();
      GEMglRasterPos4sv_setup();
      GEMglRectd_setup();
      GEMglRectf_setup();
      GEMglRecti_setup();
      GEMglRects_setup();
      GEMglRotated_setup();
      GEMglRotatef_setup();
      GEMglScaled_setup();
      GEMglScalef_setup();
      GEMglScissor_setup();
      GEMglShadeModel_setup();
      GEMglStencilFunc_setup();
      GEMglStencilMask_setup();
      GEMglStencilOp_setup();
      GEMglTexCoord1d_setup();
      GEMglTexCoord1dv_setup();
      GEMglTexCoord1f_setup();
      GEMglTexCoord1fv_setup();
      GEMglTexCoord1i_setup();
      GEMglTexCoord1iv_setup();
      GEMglTexCoord1s_setup();
      GEMglTexCoord1sv_setup();
      GEMglTexCoord2d_setup();
      GEMglTexCoord2dv_setup();
      GEMglTexCoord2f_setup();
      GEMglTexCoord2fv_setup();
      GEMglTexCoord2i_setup();
      GEMglTexCoord2iv_setup();
      GEMglTexCoord2s_setup();
      GEMglTexCoord2sv_setup();
      GEMglTexCoord3d_setup();
      GEMglTexCoord3dv_setup();
      GEMglTexCoord3f_setup();
      GEMglTexCoord3fv_setup();
      GEMglTexCoord3i_setup();
      GEMglTexCoord3iv_setup();
      GEMglTexCoord3s_setup();
      GEMglTexCoord3sv_setup();
      GEMglTexCoord4d_setup();
      GEMglTexCoord4dv_setup();
      GEMglTexCoord4f_setup();
      GEMglTexCoord4fv_setup();
      GEMglTexCoord4i_setup();
      GEMglTexCoord4iv_setup();
      GEMglTexCoord4s_setup();
      GEMglTexCoord4sv_setup();
      GEMglTexEnvf_setup();
      GEMglTexEnvi_setup();
      GEMglTexGend_setup();
      GEMglTexGenf_setup();
      GEMglTexGeni_setup();
      GEMglTexParameterf_setup();
      GEMglTexParameteri_setup();
      GEMglTranslated_setup();
      GEMglTranslatef_setup();
      GEMglVertex2d_setup();
      GEMglVertex2dv_setup();
      GEMglVertex2f_setup();
      GEMglVertex2fv_setup();
      GEMglVertex2i_setup();
      GEMglVertex2iv_setup();
      GEMglVertex2s_setup();
      GEMglVertex2sv_setup();
      GEMglVertex3d_setup();
      GEMglVertex3dv_setup();
      GEMglVertex3f_setup();
      GEMglVertex3fv_setup();
      GEMglVertex3i_setup();
      GEMglVertex3iv_setup();
      GEMglVertex3s_setup();
      GEMglVertex3sv_setup();
      GEMglVertex4d_setup();
      GEMglVertex4dv_setup();
      GEMglVertex4f_setup();
      GEMglVertex4fv_setup();
      GEMglVertex4i_setup();
      GEMglVertex4iv_setup();
      GEMglVertex4s_setup();
      GEMglVertex4sv_setup();
      GEMglViewport_setup();
   }
} // for extern "C"

