/* Base/configDarwin.h.  Generated by configure.  */


/* the maximum openGL-version to use
 * overrides the version found in the openGL-headers
 */
/* #undef GEM_OPENGL_VERSION_MAX */


/* font rendering */
#define HAVE_LIBFTGL 1

/* image loading / saving */
/* #undef HAVE_LIBMAGICKPLUSPLUS */


/* disable the use of openGL-ARB extensions */
/* #undef DONT_USE_ARB */

/* disable the use of openGL-nvidia extensions */
#define DONT_USE_NV 1

/* types, structures, compiler characteristics, ... */
#define SIZEOF_VOID_P 4
#define SIZEOF_UNSIGNED_INT 4

#define HAVE_GLSIZEIPTRARB 1
